Feature shrimp app eli part 2
EliNovakova/crevette pull request #6
Opened 2021-04-19 19:14 UTC by EliNovakova

2021-04-19 20:23 UTC, hanoskoe commented on src/shrimps/views.py
> +    last_shrimp_born = Shrimp.objects.order_by('-birth_date').first()   # orders by birth date desc, displays the first
it's better to remove the "-" and use a last() function instead of first()

2021-04-19 20:24 UTC, hanoskoe commented on src/shrimps/views.py
> +    color = choice(Shrimp.COLOR_CHOICES)
your variable color here is a tuple. Please make sure you pass a string

2021-04-19 20:25 UTC, hanoskoe commented on src/shrimps/views.py
> +    color = choice(Shrimp.COLOR_CHOICES)
your variable color here is a tuple. Please make sure you pass a string

2021-04-19 20:28 UTC, hanoskoe requested changes
sorry Eli I got a bit lost in this review stuff... I hope it's understandable anyway :) good luck

2021-04-19 20:28 UTC, hanoskoe commented on src/shrimps/views.py
> +    new_shrimp = Shrimp(name=name, size=size, weight=weight, color=color)
you could also generate a random boolean to know if the baby shrimp is farmed

2021-04-19 20:28 UTC, hanoskoe commented on src/shrimps/views.py
> +    last_shrimp_born = Shrimp.objects.order_by('-birth_date').first()   # orders by birth date desc, displays the first
it's better to remove the "-" and use a last() function instead of first()

2021-04-19 20:32 UTC, paulwalger commented on src/shrimps/views.py
> +    names = ["Max", "Cooper", "Ollie", "Walter", "Apollo", "Milo", "Billy"]
GERARD IS MISSING!

2021-04-20 20:27 UTC, hanoskoe commented on src/shrimps/views.py
> +    last_shrimp_born = Shrimp.objects.order_by('-birth_date').first()   # orders by birth date desc, displays the first
also make sure you handle the case num_shrimps=0

2021-04-24 12:00 UTC, EliNovakova commented
Finally fixed @hanoskoe :)

2021-04-24 12:02 UTC, hanoskoe commented
Looks good to me, go on with the merge!

2021-04-29 17:05 UTC, merged